import { Category, Product } from "@/types/product";

export const categories: Category[] = [
  {
    id: "all",
    name: "All Products",
    slug: "all",
    icon: "📦",
    description: "Browse the complete SAMSOJ technology catalog",
  },
  {
    id: "laptops-computers",
    name: "Laptops & Computers",
    slug: "laptops-computers",
    icon: "💻",
    description: "Desktop PCs, business laptops, gaming workstations, and all-in-one systems",
  },
  {
    id: "printers-scanners",
    name: "Printers & Scanners",
    slug: "printers-scanners",
    icon: "🖨️",
    description: "Heavy-duty laser printers, all-in-one inkjets, thermal receipt printers, and scanners",
  },
  {
    id: "networking",
    name: "Networking Equipment",
    slug: "networking",
    icon: "📡",
    description: "Enterprise routers, PoE switches, outdoor Wi-Fi APs, and Cat6 network cabling",
  },
  {
    id: "storage-hardware",
    name: "Storage & Hardware",
    slug: "storage-hardware",
    icon: "💾",
    description: "NVMe SSDs, external backup drives, RAM modules, power supplies, and internal parts",
  },
  {
    id: "cctv-security",
    name: "CCTV & Security",
    slug: "cctv-security",
    icon: "📹",
    description: "4K IP security cameras, NVR recording units, motion sensors, and security kits",
  },
  {
    id: "accessories",
    name: "Accessories & Peripherals",
    slug: "accessories",
    icon: "⌨️",
    description: "Mechanical keyboards, ergonomic mice, HDMI/VGA cables, laptop chargers, and hubs",
  },
  {
    id: "pos-equipment",
    name: "POS & Business Solutions",
    slug: "pos-equipment",
    icon: "🧾",
    description: "POS terminals, barcode scanners, cash drawers, and thermal receipt rolls",
  },
];

export const products: Product[] = [
  {
    id: "hp-elitebook-840-g8",
    name: "HP EliteBook 840 G8 / ProBook Business Laptop",
    slug: "hp-elitebook-business-laptop",
    category: "Laptops & Computers",
    categoryId: "laptops-computers",
    description:
      "Premium business-grade laptop engineered for maximum productivity, crisp display, durable chassis, and long battery life.",
    specifications: [
      "Processor: Intel Core i5 / i7 11th Gen Turbo Boost",
      "Memory: 16GB DDR4 High-Speed RAM",
      "Storage: 512GB PCIe NVMe Solid State Drive",
      "Display: 14.0-inch Full HD (1920 x 1080) Anti-Glare IPS",
      "Battery Life: Up to 10 hours with Fast Charge",
      "OS: Windows 11 Pro Genuine Licensed",
      "Connectivity: Wi-Fi 6, Bluetooth 5.0, USB-C Thunderbolt, HDMI",
    ],
    price: 485000,
    pricingType: "fixed",
    status: "available",
    image: "/products/laptops.jpg",
    featured: true,
    badge: "Popular Business Pick",
  },
  {
    id: "desktop-workstation-core-i7",
    name: "SAMSOJ Core i7 Performance Desktop PC",
    slug: "desktop-workstation-core-i7",
    category: "Laptops & Computers",
    categoryId: "laptops-computers",
    description:
      "Reliable desktop workstation customized for high-demand office operations, graphic design, school labs, and data processing.",
    specifications: [
      "Processor: Intel Core i7 High Performance CPU",
      "Memory: 16GB / 32GB DDR4 Expandable",
      "Storage: 512GB Fast SSD + 1TB Secondary HDD",
      "Graphics: Dedicated / Ultra HD Multi-Monitor Support",
      "Includes: Keyboard, Optical Mouse, Power Cables",
      "OS: Windows 10/11 Pro Pre-configured",
      "Warranty: Guaranteed Hardware Testing & Setup",
    ],
    pricingType: "contact",
    status: "available",
    image: "/products/laptops.jpg",
    featured: true,
    badge: "Custom Workstation",
  },
  {
    id: "hp-laserjet-pro-mfp",
    name: "HP LaserJet Pro Multifunction All-In-One Printer",
    slug: "hp-laserjet-pro-mfp",
    category: "Printers & Scanners",
    categoryId: "printers-scanners",
    description:
      "High-speed laser printer offering sharp monochrome printing, fast document scanning, copying, and wireless network mobile printing.",
    specifications: [
      "Functions: Print, Copy, Scan, Wireless Mobile AirPrint",
      "Print Speed: Up to 30 pages per minute (ppm)",
      "Resolution: 1200 x 1200 dpi Laser Output",
      "Duplex: Automatic Two-Sided Printing",
      "Connectivity: Wi-Fi, Ethernet Network Port, Hi-Speed USB 2.0",
      "Paper Capacity: 250-Sheet Input Tray",
    ],
    price: 320000,
    pricingType: "fixed",
    status: "available",
    image: "/products/printers.jpg",
    featured: true,
    badge: "Office Essential",
  },
  {
    id: "gigabit-poe-network-switch-router",
    name: "Gigabit Dual-Band Router & PoE Managed Network Switch",
    slug: "gigabit-network-switch-router",
    category: "Networking Equipment",
    categoryId: "networking",
    description:
      "Enterprise-grade networking equipment designed for stable internet distribution, high-bandwidth streaming, and secure office connectivity.",
    specifications: [
      "Router: Dual-Band AC1200 / AX3000 Wi-Fi 6 Router",
      "Switch: 8-Port / 16-Port Gigabit Power over Ethernet (PoE)",
      "Bandwidth: Up to 1000 Mbps throughput per port",
      "Security: WPA3 Encryption, SPI Firewall, Guest Network",
      "Ideal For: Offices, cyber cafes, schools, and smart homes",
    ],
    pricingType: "contact",
    status: "available",
    image: "/products/networking.jpg",
    featured: true,
    badge: "Enterprise Grade",
  },
  {
    id: "high-speed-nvme-ssd-backup",
    name: "Samsung / Kingston High-Speed NVMe SSD & External Backup Drives",
    slug: "nvme-ssd-external-backup",
    category: "Storage & Hardware",
    categoryId: "storage-hardware",
    description:
      "Ultra-fast solid-state drives and portable rugged external hard drives to boost your PC speed and secure your critical files.",
    specifications: [
      "Capacities Available: 256GB, 512GB, 1TB, 2TB, 4TB",
      "Read Speeds: Up to 3,500 MB/s (NVMe PCIe Gen3/Gen4)",
      "Form Factor: M.2 2280 NVMe / 2.5-inch SATA III / USB 3.2 External",
      "Compatibility: Laptops, Desktop PCs, MacBooks, PS5 / Consoles",
      "Shock Resistant: Built for long-term file security and reliability",
    ],
    price: 45000,
    pricingType: "fixed",
    status: "available",
    image: "/products/storage.jpg",
    featured: false,
    badge: "Speed Upgrade",
  },
  {
    id: "cctv-night-vision-security-kit",
    name: "4K Ultra HD Night Vision CCTV Camera Surveillance Kit",
    slug: "cctv-night-vision-security-kit",
    category: "CCTV & Security",
    categoryId: "cctv-security",
    description:
      "Comprehensive multi-camera security system with crystal clear day/night vision, smartphone remote viewing, and intelligent motion detection.",
    specifications: [
      "Cameras: 4 / 8 Waterproof Weatherproof HD Infrared Cameras",
      "Recording: 4K NVR/DVR with 1TB / 2TB Surveillance Hard Drive",
      "Night Vision: Smart IR LEDs up to 30 meters range",
      "Mobile Access: Real-time live view & alerts on Android & iOS",
      "Installation: Professional onsite setup and cabling available",
    ],
    pricingType: "contact",
    status: "available",
    image: "/products/pos.jpg",
    featured: true,
    badge: "Complete Security",
  },
  {
    id: "pos-terminal-barcode-scanner",
    name: "Complete Point of Sale (POS) Terminal & Barcode Scanner System",
    slug: "pos-terminal-barcode-system",
    category: "POS & Business Solutions",
    categoryId: "pos-equipment",
    description:
      "All-in-one POS hardware setup for retail supermarkets, pharmacy stores, restaurants, and electronics shops.",
    specifications: [
      "Includes: Touchscreen POS Terminal / PC, Thermal Receipt Printer, Handheld Barcode Scanner, Heavy-Duty Cash Drawer",
      "Scanner: 1D / 2D QR Code High-Speed Laser Reader",
      "Printer: 80mm High-Speed Auto-Cutter Thermal Printer",
      "Compatibility: Works with all leading inventory & retail software",
    ],
    pricingType: "contact",
    status: "available",
    image: "/products/pos.jpg",
    featured: false,
    badge: "Retail & Shop Ready",
  },
  {
    id: "essential-computer-accessories-pack",
    name: "Premium Keyboard, Wireless Mouse, Power Surge Protector & Cables",
    slug: "essential-computer-accessories",
    category: "Accessories & Peripherals",
    categoryId: "accessories",
    description:
      "Genuine computer accessories, ergonomic peripherals, heavy-duty surge protectors, and original replacement power adapters.",
    specifications: [
      "Keyboard & Mouse: Ergonomic Quiet-Key Wireless / USB Sets",
      "Power Protection: Multi-Socket Surge Protector with USB Ports",
      "Cables: Gold-Plated 4K HDMI, DisplayPort, VGA, Cat6 Patch Cords",
      "Adapters: Universal Laptop Chargers (HP, Dell, Lenovo, Toshiba)",
    ],
    price: 18500,
    pricingType: "fixed",
    status: "available",
    image: "/products/accessories.jpg",
    featured: false,
    badge: "In Stock",
  },
];